import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { randomBytes } from "node:crypto";
import { fileURLToPath } from "node:url";
import { runMigrations } from "./migrate.mjs";

const DATABASE_ID = "orp_db";
const DATABASE_NAME = "Open Rockets Press";

function parseArgs() {
  const args = process.argv.slice(2);
  const read = (flag) => {
    const index = args.indexOf(flag);
    return index >= 0 ? args[index + 1] : null;
  };

  return {
    endpoint: read("--endpoint") || process.env.APPWRITE_ENDPOINT || "",
    apiKey: read("--api-key") || process.env.APPWRITE_API_KEY || "",
    projectId: read("--project") || process.env.APPWRITE_PROJECT_ID || "",
  };
}

async function appwriteRequest({ endpoint, apiKey, projectId, method, resourcePath, body }) {
  const response = await fetch(`${endpoint}${resourcePath}`, {
    method,
    headers: {
      "Content-Type": "application/json",
      "X-Appwrite-Key": apiKey,
      ...(projectId ? { "X-Appwrite-Project": projectId } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  const text = await response.text();
  let data = null;
  if (text) {
    try {
      data = JSON.parse(text);
    } catch {
      data = text;
    }
  }

  return { ok: response.ok, status: response.status, data };
}

async function ensureDatabase({ endpoint, apiKey, projectId }) {
  const existing = await appwriteRequest({
    endpoint,
    apiKey,
    projectId,
    method: "GET",
    resourcePath: `/databases/${DATABASE_ID}`,
  });

  if (existing.ok) {
    console.log(`[setup] Database ${DATABASE_ID} already exists`);
    return;
  }

  const created = await appwriteRequest({
    endpoint,
    apiKey,
    projectId,
    method: "POST",
    resourcePath: "/databases",
    body: {
      databaseId: DATABASE_ID,
      name: DATABASE_NAME,
    },
  });

  if (!created.ok) {
    throw new Error(`Failed to create database: ${JSON.stringify(created.data)}`);
  }

  console.log(`[setup] Created database ${DATABASE_ID}`);
}

function writeEnvFile(vars) {
  const currentDir = path.dirname(fileURLToPath(import.meta.url));
  const rootDir = path.resolve(currentDir, "..");
  const envPath = path.join(rootDir, ".env.local");

  const lines = [
    "# Auto-generated by migrations/setup.mjs",
    "# Do not commit this file",
    "",
    ...Object.entries(vars).map(([key, value]) => `${key}=${value}`),
    "",
  ];

  fs.writeFileSync(envPath, lines.join("\n"), "utf8");
  console.log(`[setup] Wrote ${envPath}`);
}

async function main() {
  const parsed = parseArgs();
  if (!parsed.endpoint || !parsed.apiKey || !parsed.projectId) {
    console.error(
      "Usage: node migrations/setup.mjs --endpoint <url> --api-key <key> --project <project_id>",
    );
    process.exit(1);
  }

  const endpoint = parsed.endpoint.replace(/\/+$/, "");

  await ensureDatabase({ endpoint, apiKey: parsed.apiKey, projectId: parsed.projectId });

  process.env.APPWRITE_ENDPOINT = endpoint;
  process.env.APPWRITE_PROJECT_ID = parsed.projectId;
  process.env.APPWRITE_API_KEY = parsed.apiKey;
  process.env.APPWRITE_DATABASE_ID = DATABASE_ID;

  await runMigrations({ strict: true });

  writeEnvFile({
    APPWRITE_ENDPOINT: endpoint,
    APPWRITE_PROJECT_ID: parsed.projectId,
    APPWRITE_API_KEY: parsed.apiKey,
    APPWRITE_DATABASE_ID: DATABASE_ID,
    APP_BASE_URL: "https://press.openrockets.com",
    CONSENT_TOKEN_SECRET: randomBytes(32).toString("hex"),
    APPWRITE_BUCKET_PUB_FILES: "pub_files",
    APPWRITE_BUCKET_PUB_COVERS: "pub_covers",
    APPWRITE_BUCKET_CASE_ATTACHMENTS: "case_attachments",
    PLAUSIBLE_DOMAIN: "press.openrockets.com",
    PLAUSIBLE_API_KEY: "# TODO",
  });

  console.log("[setup] Bootstrap complete.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
