export interface Env {
  APPWRITE_ENDPOINT: string;
  APPWRITE_PROJECT_ID: string;
  APPWRITE_API_KEY: string;
  APPWRITE_DATABASE_ID: string;
  APP_BASE_URL: string;
  CONSENT_TOKEN_SECRET: string;
  GUARDIAN_EMAIL_SECRET: string;
  APPWRITE_BUCKET_PUB_FILES: string;
  APPWRITE_BUCKET_PUB_COVERS: string;
  APPWRITE_BUCKET_CASE_ATTACHMENTS: string;
  PLAUSIBLE_DOMAIN?: string;
  PLAUSIBLE_API_KEY?: string;
}
